### ISSUE TITLE
all_processed_segs needs to rename/refunction to conform to e_seg and / or f_sort

### ISSUE THREAD

**Issue by rcrath** [rcrath/wavetabler#14]
wavecycle_samples_target_mode not sticking. no value or value not passed.

**Comment by rcrath** [comment]
after removing refs to all_segment_sizes, I now get this error for defaults:
```
full_path: flange220-stereo\tmp\cpy\flange220-stereo.wav
Segmentation complete. Total segments: 436
All segments passed validation.
Traceback (most recent call last):
  File "E:\Dropbox\audio\wavetables\wavetabler\src\a_wvtbl.py", line 79, in <module>
    main()
  File "E:\Dropbox\audio\wavetables\wavetabler\src\a_wvtbl.py", line 75, in main
    process_single_file(file_name)
  File "E:\Dropbox\audio\wavetables\wavetabler\src\a_wvtbl.py", line 56, in process_single_file
    aa_common.global_settings, 0, 0, 0, 0, True, processed_files, wavecycle_samples_target_mode
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'wavecycle_samples_target_mode' where it is not associated with a value

```
and this error when I choose autocorrelate.
```
Choose or press enter for default:2
Best interval: 218 samples (mode of intervals), Confidence: 0.35
File: flange220-stereo\tmp\cpy\flange220-stereo.wav
Mode Interval: 218 samples, Count: 11
Neighbors: 30
Confidence: 0.3548387096774194
Frequency: 220.1834862385321 Hz
Found 431 relevant peaks for segmentation.
Skipping e_seg and proceeding directly to f_sort.
Traceback (most recent call last):
  File "E:\Dropbox\audio\wavetables\wavetabler\src\a_wvtbl.py", line 79, in <module>
    main()
  File "E:\Dropbox\audio\wavetables\wavetabler\src\a_wvtbl.py", line 75, in main
    process_single_file(file_name)
  File "E:\Dropbox\audio\wavetables\wavetabler\src\a_wvtbl.py", line 55, in process_single_file
    total_segments, total_deviant_segments, total_normal_segments, total_attack_segments, lower_bound_samples, upper_bound_samples = f_sort.run(
                                                                                                                                     ^^^^^^^^^^^
  File "E:\Dropbox\audio\wavetables\wavetabler\src\f_sort.py", line 154, in run
    mode_frequency = 192000 / wavecycle_samples_target_mode
                     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
```
