### ISSUE TITLE
h_interpolate "wavecycle_samples_target" variable not set properly

### ISSUE THREAD

**Issue by rcrath** [rcrath/wavetabler#19]
```
Do you want to keep normal segments? (Y/n):
Traceback (most recent call last):
  File "E:\Dropbox\audio\wavetables\wavetabler\src\a_wvtbl.py", line 79, in <module>
    main()
  File "E:\Dropbox\audio\wavetables\wavetabler\src\a_wvtbl.py", line 75, in main
    process_single_file(file_name)
  File "E:\Dropbox\audio\wavetables\wavetabler\src\a_wvtbl.py", line 63, in process_single_file
    h_interpolate.run(total_segments, total_deviant_segments, total_normal_segments, total_attack_segments, aa_common.global_settings)
  File "E:\Dropbox\audio\wavetables\wavetabler\src\h_interpolate.py", line 30, in run
    raise ValueError("Invalid wavecycle_samples_target: It must be a positive non-zero value.")
ValueError: Invalid wavecycle_samples_target: It must be a positive non-zero value.
```

**Comment by rcrath** [comment]
```
Selected: bam-damp-Gmetala.wav

Accept all defaults (try this first!) Y/n: n

Choose a method of segmenting the file {cpy_path}

     1. Zero Crossing (default): good for percussive sounds
        and sounds with multiple or unclear pitches.

     2. Autocorrelation: for clearly single pitched sounds

Choose or press enter for default (patience, it may take a while): 2
Best interval: 975 samples (mode of intervals), Confidence: 0.43
Skipping e_seg and proceeding directly to f_sort.
wavecycle_samples_target_mode: 975

Choose the dominant frequency. If you aren't sure, press ENTER or 1.

1. Set to the MODE (G3+8 / 196.92Hz / 975 samples)

2. Open the graph to select VISUALLY

3. Enter a musical NOTE (e.g., A4, C#3) or a frequency in Hz

Press Enter, 1, 2 or 3 to choose: 2

Valid segment range within +/-5% tolerance: 0 to 0 samples.
    Number of attack segments.............................. 0 (0 < tolerance < 0)
    Number of normal segments.............................. 516 (0 < 0 exactly 0 samples < 516)
    Number of deviant segments............................. 0 (0 < tolerance < 0)
===============================================================================
    Total number of wavetable segments (all)............... 516

Do you want to accept all current settings? (Y/n):
Proceeding with current settings...

Do you want to keep attack segments? (Y/n):
Do you want to keep deviant segments? (Y/n):
Do you want to keep normal segments? (Y/n):
Traceback (most recent call last):
  File "E:\Dropbox\audio\wavetables\wavetabler\src\a_wvtbl.py", line 79, in <module>
    main()
  File "E:\Dropbox\audio\wavetables\wavetabler\src\a_wvtbl.py", line 75, in main
    process_single_file(file_name)
  File "E:\Dropbox\audio\wavetables\wavetabler\src\a_wvtbl.py", line 63, in process_single_file
    h_interpolate.run(total_segments, total_deviant_segments, total_normal_segments, total_attack_segments, aa_common.global_settings)
  File "E:\Dropbox\audio\wavetables\wavetabler\src\h_interpolate.py", line 30, in run
    raise ValueError("Invalid wavecycle_samples_target: It must be a positive non-zero value.")
ValueError: Invalid wavecycle_samples_target: It must be a positive non-zero value.

(wvtbl_win) E:\Dropbox\audio\wavetables\wavetabler
```
